### ISSUE TITLE
Angular Not Defined Error

### ISSUE THREAD

**Issue by anveshnara** [cowbell/ionic-geofence#23] opened 2016-08-29 11:24 UTC
Angular Not Defined Error in console while debugger when place script url then injection error occur in console

**Comment by tsubik** [comment] 2017-01-22 11:13
Not sure what the problem is, could you please describe step by step instruction to reproduce this bug? Closing for now, please feel free to reopen if the problem still occurs, but with more information.

**Closed by tsubik** 2017-01-22 11:13 UTC
