### ISSUE TITLE
Xcode 8, iOS 10 compatbility issue

### ISSUE THREAD

**Issue by echotech11** [cowbell/ionic-geofence#24] opened 2016-09-24 02:41 UTC
This plugin is no longer allowing me to build on ionic/cordova using xcode 8 for iOS 10.

**Comment by videmort** [comment] 2016-10-14 22:36
yes is not working for me too

**Comment by videmort** [comment] 2016-10-23 11:20
hi @echotech11 the problem is becaous xcode 8 need swift 2.3 and the plugin is not prepared for that. I updated the plugin to swift 2.3  and is ready now :) https://github.com/cowbell/cordova-plugin-geofence/commit/5a09cac93379aa4f6a7be08148166510b29c0571

**Comment by tsubik** [comment] 2017-02-26 10:25
Should be fixed in #02fb2a1. Plugins have to be reinstalled.

```
ionic state clear
ionic platform add ios
```

**Closed by tsubik** 2017-02-26 10:25 UTC
